### ISSUE TITLE
Error occurred when executing ADMD_TrainLora: Expected is_sm80 to be true, but got false.

### ISSUE THREAD

**Issue by gordingus** [kijai/ComfyUI-ADMotionDirector#2]
Using your included workflow example: 

![image](https://github.com/kijai/ComfyUI-ADMotionDirector/assets/121201788/0be8ca2f-1a1b-4834-96b8-f4a5736331e8)

**Comment by kijai** [comment]
Which GPU do you have? I think the underlaying training code has some requirements for that.

**Comment by gordingus** [comment]
I've got a 3090, normally good with all things AI

**Comment by kijai** [comment]
It should definitely work on that, it "works" on my 3080 even, just not in any useable resolutions. 
So it's got to be your pytorch/cuda/nvidia driver version or something, probably pytorch. I've only tested with 2.1 and up and cu121

**Comment by gordingus** [comment]
Sorry, you can close this! Uninstalling old torch and installing 2.2.0 with cu121 and new xformers 0.0.24 fixed it
