### ISSUE TITLE
[Feature Suggestion]Multi videos training 

### ISSUE THREAD

**Issue by cheezecrisp** [kijai/ComfyUI-ADMotionDirector#6]
I guess it would be less overfit if we train with several videos

**Comment by kijai** [comment]
It should already have been possible, you just train some steps with one video, then with another and so on. Granted it was clumsy to setup, and I never tried it, but I added image input to the Train nodes now to make it bit simpler, reach train node can have different batch.

**Comment by kijai** [comment]
This is currently in dev branch and seems to be working, the videos are cycled through each step, for example with 2 videos, 100 steps, it will do 50 with each alternating.

**Comment by cheezecrisp** [comment]
> This is currently in dev branch and seems to be working, the videos are cycled through each step, for example with 2 videos, 100 steps, it will do 50 with each alternating.

Great, I'll check it out.

**Comment by kijai** [comment]
This is now in main.
