### ISSUE TITLE
The size of tensor a (54) must match the size of tensor b (32) at non-singleton dimension 1

### ISSUE THREAD

**Issue by andyvha** [kijai/ComfyUI-ADMotionDirector#7]
Hi,

When I use your node, running and got this issue:

ComfyUI-ADMotionDirector/animatediff/models/motion_module.py", line 251, in forward
    x = x + self.pe[:, :x.size(1)]
RuntimeError: The size of tensor a (54) must match the size of tensor b (32) at non-singleton dimension 1

I changed size to smaller or square size like 512... but it still raise issue. I use SD1.5 model. I use pytorch 2.1.2+cuda121

![image](https://github.com/kijai/ComfyUI-ADMotionDirector/assets/40895228/60d1b888-0a30-41e7-a4c3-8a0338db707c)

**Comment by kijai** [comment]
What motion model is that you have selected there?

**Comment by andyvha** [comment]
I use v3_sd15_mm and v3_sd15_adapter

![image](https://github.com/kijai/ComfyUI-ADMotionDirector/assets/40895228/ae45d60e-c6c9-42c1-9899-c5aaaa44e561)

**Comment by andyvha** [comment]
I update to diffusers 0.27.2 and issue gone. Others face with this issue please upgrade diffusers.
